# Modern Docker Compose (no version needed)

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      # Environment variables from .env file
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - WEAVIATE_API_KEY=${WEAVIATE_API_KEY:-}
      - WEAVIATE_URL=${WEAVIATE_URL:-}
      - FORCE_MOCK=${FORCE_MOCK:-false}
      - DEBUG=${DEBUG:-true}
    volumes:
      - ./backend:/app
      - ./config:/app/config
      - ./.env:/app/.env:ro  # Mount .env file for security detection
    command: uv run fastapi dev api/routes.py --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=4321
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4321/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Nginx for production routing
  nginx:
    image: nginx:alpine
    ports:
      - "2872:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    # Disable health check - nginx is working fine, health check is causing spam
    # healthcheck:
    #   test: ["CMD", "nginx", "-t"]
    #   interval: 15s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 5s
    restart: unless-stopped